version: '3.7'

services:

  service:
    container_name: billing_api
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-api:{{ env.IMAGE_TAG }}
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010 --access-log
    ports:
      - "8010"
    environment:
      PROJECT_NAME: {{ env.PROJECT_NAME }}
      DB_HOST: {{ env.DB_HOST }}
      DB_PORT: {{ env.DB_PORT }}
      YOOKASSA_ACCOUNT_ID: {{ env.YOOKASSA_ACCOUNT_ID }}
      YOOKASSA_SECRET_KEY: {{ env.YOOKASSA_SECRET_KEY }}
      DATABASE_URL: {{ env.DATABASE_URL }}
    depends_on:
      - db

  db:
    container_name: billing_db
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: {{ env.POSTGRES_DB }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_USER: {{ env.POSTGRES_USER }}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: billing_nginx
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-nginx:{{ env.IMAGE_TAG }}
    volumes:
      - certbot-conf:/etc/nginx/ssl/:ro
      - certbot-www:/var/www/certbot/:ro
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt/:rw
      - certbot-www:/var/www/certbot/:rw

volumes:
  postgres_data:
  certbot-conf:
  certbot-www:
