version: '3.7'

services:

  service:
    container_name: billing_api
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010 --access-log
    build:
      context: api/src/app
      dockerfile: ./Dockerfile
    ports:
      - "8010"
    env_file:
      - .env
    depends_on:
      - db

  auth_service:
    container_name: auth_api
    build:
      context: auth_api/src
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: src/app/app.py
    entrypoint: >
      sh -c "python src/app/utils/wait_for_pg.py && python src/app/utils/wait_for_redis.py && python -m flask db upgrade  && sleep 5 && python -m flask run --host 0.0.0.0 --port 8001 --debugger"
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      - db

  jaeger:
    container_name: jaeger_auth
    image: jaegertracing/all-in-one:latest
    ports:
      - "6833:6833/udp"
      - "16686:16686"

  redis:
    container_name: redis_auth
    build:
      context: auth_api/redis
      dockerfile: ./Dockerfile
    depends_on:
      - auth_service
    ports:
      - "6380:6380"

  db:
    container_name: billing_db
    build:
      context: postgres
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    container_name: billing_nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - service

volumes:
  postgres_data: