version: '3.7'

services:

  service:
    container_name: billing_api
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-api:1.0.0
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010 --access-log
    ports:
      - "8010"
    depends_on:
      - db

  db:
    container_name: billing_db
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: billing_nginx
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-nginx:1.0.0
    ports:
      - "80:80"
    depends_on:
      - service

volumes:
  postgres_data:
