version: '3.7'

services:

  service:
    container_name: billing_api
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-api:${IMAGE_TAG}
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8010 --access-log
    ports:
      - "8010"
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      YOOKASSA_ACCOUNT_ID: ${YOOKASSA_ACCOUNT_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    container_name: billing_db
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: billing_nginx
    image: cr.yandex/crpis5t0f3nv1ncr2fe9/billing-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - service

volumes:
  postgres_data:
