# Generated by Django 3.2 on 2022-07-20 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS admin;',
            reverse_sql='DROP SCHEMA IF EXISTS admin CASCADE;',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, verbose_name='username')),
                ('cart', models.JSONField(verbose_name='cart')),
                ('provider', models.CharField(db_index=True, max_length=20, verbose_name='payment system')),
                ('payment_status', models.CharField(max_length=50, verbose_name='payment status')),
                ('paid', models.BooleanField(verbose_name='paid')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'admin"."payment',
            },
        ),
    ]
