# Generated by Django 3.2 on 2022-07-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='provider',
            new_name='payment_system',
        ),
    ]
