version: '3.8'

services:
  db:
    container_name: billing_db
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

volumes:
  postgres_data:
    name: billing_admin
