# Generated by Django 3.2 on 2022-07-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO admin.product (id, name, description, type, created_at, updated_at)
                VALUES
                ('35524a26-384c-419c-919d-22c81729e112', '1 month', 'Buy 1 month subscription', 'subscription', '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('e0278be7-aebf-4f89-941a-2976aeb86659', '3 months', 'Buy 3 months subscription', 'subscription', '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('0ea4d475-af14-4f8e-a2cd-866f72274184', '6 months', 'Buy 6 months subscription', 'subscription', '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('84aba86e-6431-4da2-9975-0d960f21b6ef', '1 year', 'Buy 1 year subscription', 'subscription', '07/27/2022, 22:36:36', '07/27/2022, 22:36:36');
                INSERT INTO admin.price (id, product_id, value, currency, description, is_active, created_at, updated_at)
                VALUES
                ('3b3c37ba-5cab-42ba-97e8-7c158f921ae0', '35524a26-384c-419c-919d-22c81729e112', 250.0, 'RUB', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('525f88e6-5fe5-4676-9213-e3469a56c2cc', '35524a26-384c-419c-919d-22c81729e112', 200.0, 'RUB', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('c1d63531-1a5e-4167-9834-8e99342e3510', '35524a26-384c-419c-919d-22c81729e112', 4.17, 'USD', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('dabe05ba-94f2-4ed5-a75d-87a486468764', '35524a26-384c-419c-919d-22c81729e112', 3.33, 'USD', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('1f01277e-b5f7-4df8-a785-b7cd22e706ed', '35524a26-384c-419c-919d-22c81729e112', 27.17, 'CNY', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('96b0ee30-5e84-435d-80bd-3020540107dc', '35524a26-384c-419c-919d-22c81729e112', 21.74, 'CNY', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('b33e8346-6edc-4a0b-a0d0-140aeda272ba', '35524a26-384c-419c-919d-22c81729e112', 0.00231, 'ETH', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('4065d5c4-5500-4b8e-9e14-baa2bf6b834f', '35524a26-384c-419c-919d-22c81729e112', 0.00185, 'ETH', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('41f95b7f-6196-43f7-b47a-551199ed7284', 'e0278be7-aebf-4f89-941a-2976aeb86659', 225.0, 'RUB', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('aa7c7806-880c-4000-b8eb-2e04c1b0818a', 'e0278be7-aebf-4f89-941a-2976aeb86659', 180.0, 'RUB', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('789ad6d3-928f-4c66-95d4-62fe314c3feb', 'e0278be7-aebf-4f89-941a-2976aeb86659', 3.75, 'USD', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('c1e259a0-b5c1-49bc-bd4e-fa131403a7ed', 'e0278be7-aebf-4f89-941a-2976aeb86659', 3.0, 'USD', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('425792cf-a6f1-4fb8-8195-8f6badd17515', 'e0278be7-aebf-4f89-941a-2976aeb86659', 24.46, 'CNY', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('dccb740b-799c-494a-af4d-5b76d4faf2cd', 'e0278be7-aebf-4f89-941a-2976aeb86659', 19.57, 'CNY', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('323fdae7-45c3-4aaa-b98d-1b7bff4cc9bf', 'e0278be7-aebf-4f89-941a-2976aeb86659', 0.00208, 'ETH', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('d2592a15-844a-447a-a38d-8ba2dc3b8473', 'e0278be7-aebf-4f89-941a-2976aeb86659', 0.00167, 'ETH', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('29bcb3b0-30ec-4889-af76-282d79ca6351', '0ea4d475-af14-4f8e-a2cd-866f72274184', 200.0, 'RUB', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('20676d24-e068-4d87-8d9e-8cb37d756045', '0ea4d475-af14-4f8e-a2cd-866f72274184', 160.0, 'RUB', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('c61c916c-1fa4-4c31-ad2f-b88ff275c6ce', '0ea4d475-af14-4f8e-a2cd-866f72274184', 3.33, 'USD', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('1e2bcfd6-96aa-4386-a7ca-2c30ee0055a4', '0ea4d475-af14-4f8e-a2cd-866f72274184', 2.67, 'USD', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('a2dfa970-a210-4dfe-b2bf-69d7052571c7', '0ea4d475-af14-4f8e-a2cd-866f72274184', 21.74, 'CNY', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('1e2ad004-a996-4ca1-87c1-e79c212a231a', '0ea4d475-af14-4f8e-a2cd-866f72274184', 17.39, 'CNY', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('fb5b2be5-2009-48bf-8ee3-adff34cc740e', '0ea4d475-af14-4f8e-a2cd-866f72274184', 0.00185, 'ETH', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('9dabded5-3ddc-444f-9104-f4cd81ab928b', '0ea4d475-af14-4f8e-a2cd-866f72274184', 0.00148, 'ETH', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('0725b1ce-b9ac-4496-b992-3eb265a83efb', '84aba86e-6431-4da2-9975-0d960f21b6ef', 175.0, 'RUB', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('c360ea02-66ab-441a-8e5a-98be5eba48d2', '84aba86e-6431-4da2-9975-0d960f21b6ef', 140.0, 'RUB', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('87e58ebd-9847-4f16-80b5-797ae8d52fb5', '84aba86e-6431-4da2-9975-0d960f21b6ef', 2.92, 'USD', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('3e4286a2-4172-464b-97a8-b48497dd514b', '84aba86e-6431-4da2-9975-0d960f21b6ef', 2.33, 'USD', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('5a45aad5-8d86-4762-b0a1-7b41a7a2aa83', '84aba86e-6431-4da2-9975-0d960f21b6ef', 19.02, 'CNY', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('e4c46ef5-0c40-42c5-9ef2-371b1bbf3874', '84aba86e-6431-4da2-9975-0d960f21b6ef', 15.22, 'CNY', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('bb0ffc7b-4876-4e92-92f3-5ed0d7c37f46', '84aba86e-6431-4da2-9975-0d960f21b6ef', 0.00162, 'ETH', 'default price', False, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36'),
                ('2669fd75-6b3a-4143-bef9-f86ef92ff8ea', '84aba86e-6431-4da2-9975-0d960f21b6ef', 0.0013, 'ETH', 'chinese new year sale', True, '07/27/2022, 22:36:36', '07/27/2022, 22:36:36');
            """,
            reverse_sql="""
                TRUNCATE TABLE admin.product;
                TRUNCATE TABLE admin.price;
            """,
        )
    ]
