# Generated by Django 3.2 on 2022-07-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO admin.product (id, name, description, type, created_at, updated_at)
                VALUES
                ('28963e6e-c49c-47df-8539-cb5b704d3588', '1 month', 'Buy 1 month subscription', 'subscription', '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('d7135d34-6e10-46da-a33b-154fe50921bf', '3 months', 'Buy 3 months subscription', 'subscription', '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('d59f0a16-bbbf-43ac-a28d-3619a50744de', '6 months', 'Buy 6 months subscription', 'subscription', '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('f98a9836-dc0a-495c-a1e7-7966e91265aa', '1 year', 'Buy 1 year subscription', 'subscription', '07/26/2022, 20:02:36', '07/26/2022, 20:02:36');
                INSERT INTO admin.price (id, product_id, value, currency, description, is_active, created_at, updated_at)
                VALUES
                ('7dd9f359-e729-4007-bfb1-387ae174aac9', '28963e6e-c49c-47df-8539-cb5b704d3588', 250.0, 'RUB', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('42728c2c-6ae5-4773-a7ad-d835ff668667', '28963e6e-c49c-47df-8539-cb5b704d3588', 200.0, 'RUB', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('e4fc600c-ca4f-4e9b-b392-274bf66d09fe', '28963e6e-c49c-47df-8539-cb5b704d3588', 4.17, 'USD', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('8ccdd91e-7033-4489-bfc6-a0c40cb033f9', '28963e6e-c49c-47df-8539-cb5b704d3588', 3.33, 'USD', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('0f273776-b4c3-4c57-a211-7ce9b7796ba3', '28963e6e-c49c-47df-8539-cb5b704d3588', 27.17, 'CNY', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('8dad8efa-7967-464e-953e-b3c81751fba3', '28963e6e-c49c-47df-8539-cb5b704d3588', 21.74, 'CNY', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('b99f909a-18d8-482e-a8a3-1ccb8fa75ba7', '28963e6e-c49c-47df-8539-cb5b704d3588', 0.00231, 'ETH', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('bcc35b9a-e74a-4d8a-8cde-be0a6757b239', '28963e6e-c49c-47df-8539-cb5b704d3588', 0.00185, 'ETH', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('951fc182-fd73-4bd6-9de0-44c70480e09b', 'd7135d34-6e10-46da-a33b-154fe50921bf', 675.0, 'RUB', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('4dbe7da2-3922-48bc-a6a9-626921817686', 'd7135d34-6e10-46da-a33b-154fe50921bf', 540.0, 'RUB', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('f87fac34-5630-4b22-b625-ef7551128cc5', 'd7135d34-6e10-46da-a33b-154fe50921bf', 11.25, 'USD', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('93d7f125-644b-4277-b1ef-d8ce2de124a8', 'd7135d34-6e10-46da-a33b-154fe50921bf', 9.0, 'USD', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('242d5de2-2192-4e86-890f-c078f32eff1c', 'd7135d34-6e10-46da-a33b-154fe50921bf', 73.37, 'CNY', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('3e174d34-a250-4872-b4fb-27a337cf2f5c', 'd7135d34-6e10-46da-a33b-154fe50921bf', 58.7, 'CNY', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('682e67b0-7b23-46e3-b384-a32a2abaf8af', 'd7135d34-6e10-46da-a33b-154fe50921bf', 0.00625, 'ETH', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('01e3139f-c687-46e6-ac64-b356784d9900', 'd7135d34-6e10-46da-a33b-154fe50921bf', 0.005, 'ETH', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('a19930ce-4e0c-4f6d-970c-87cb9d7ed944', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 1200.0, 'RUB', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('ea50be90-54e8-40d5-b099-d8084e3f981d', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 960.0, 'RUB', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('5d3d12f0-ec61-4f40-a128-3590e4074c8d', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 20.0, 'USD', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('15d70831-4554-4084-980d-030175c439ea', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 16.0, 'USD', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('afc51b85-8c6a-4ba7-9f76-bcbc4b637b15', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 130.43, 'CNY', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('287813d3-a35c-4b0e-969f-33e2c0b185d4', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 104.35, 'CNY', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('0863c125-2114-4843-a883-654817c79a98', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 0.01111, 'ETH', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('295fa5b2-f4a5-4689-a174-cc20d84f36b3', 'd59f0a16-bbbf-43ac-a28d-3619a50744de', 0.00889, 'ETH', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('01cbdc37-5a78-441f-aa4f-9c40374d593f', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 2100.0, 'RUB', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('b05730cb-7151-4d83-a57a-f89b59546fba', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 1680.0, 'RUB', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('99315312-a895-4117-ab9f-2b75e1157d1c', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 35.0, 'USD', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('68401bc8-dbd9-47a2-946b-495ea5413e00', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 28.0, 'USD', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('9b88ca89-62d4-43f7-a27b-6ce58d69b115', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 228.26, 'CNY', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('225a793d-ff7b-4091-b1bc-4a383bae8338', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 182.61, 'CNY', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('0d14f77e-23e4-4a0e-bfda-e4d9fe2228ad', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 0.01944, 'ETH', 'default price', False, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36'),
                ('4b4305b8-bb7e-41aa-8856-4874f9a5942f', 'f98a9836-dc0a-495c-a1e7-7966e91265aa', 0.01556, 'ETH', 'china new year sale', True, '07/26/2022, 20:02:36', '07/26/2022, 20:02:36');
            """,
            reverse_sql="""
                TRUNCATE TABLE admin.product;
                TRUNCATE TABLE admin.price;
            """,
        )
    ]
