# Generated by Django 3.2 on 2022-07-24 17:25

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_provider_payment_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('value', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='product price')),
                ('currency', models.CharField(max_length=5, verbose_name='product currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'admin"."product',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ManyToManyField(related_name='payments', to='billing.Product', verbose_name='cart'),
        ),
    ]
