name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image billing-api
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f api/src/app/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./api/src/app
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-nginx
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-nginx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f nginx/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./nginx
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-auth
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-auth
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f auth_api/src/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./auth_api/src/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-postgres
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-postgres
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f postgres/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./postgres
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG   

      - name: Build, tag, and push image billing-redis
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-redis
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f auth_api/redis/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./auth_api/redis
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-admin
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-admin
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f admin/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./admin
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-logstash
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-logstash
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f elk/logstash/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./elk/logstash
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image billing-filebeat
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-filebeat
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build -f elk/filebeat/Dockerfile -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./elk/filebeat
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1
        env:
          CR_REGISTRY: crpis5t0f3nv1ncr2fe9
          CR_REPOSITORY: billing-repo
          IMAGE_TAG: ${{ github.sha }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          # Postgres
          POSTGRES_MULTIPLE_DATABASES: ${{ secrets.POSTGRES_MULTIPLE_DATABASES }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          # Billing srvice
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          DB_HOST_BILLING: ${{ secrets.DB_HOST_BILLING }}
          DB_PORT_BILLING: ${{ secrets.DB_PORT_BILLING }}
          DB_NAME_BILLING: ${{ secrets.DB_NAME_BILLING }}
          YOOKASSA_ACCOUNT_ID: ${{ secrets.YOOKASSA_ACCOUNT_ID }}
          YOOKASSA_SECRET_KEY: ${{ secrets.YOOKASSA_SECRET_KEY }}
          YOOKASSA_ACCESS_TOKEN: ${{ secrets.YOOKASSA_ACCESS_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUTH_URL: ${{ secrets.AUTH_URL }}
          AUTH_SYNC_PATH: ${{ secrets.AUTH_SYNC_PATH }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          ADMIN_URL: ${{ secrets.ADMIN_URL }}
          ADMIN_SYNC_PATH: ${{ secrets.ADMIN_SYNC_PATH }}
          ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          # Auth service
          DB_HOST_AUTH: ${{ secrets.DB_HOST_AUTH }}
          DB_PORT_AUTH: ${{ secrets.DB_PORT_AUTH }}
          DB_NAME_AUTH: ${{ secrets.DB_NAME_AUTH }}
          ACCESS_TOKEN_EXPIRED: ${{ secrets.ACCESS_TOKEN_EXPIRED }}
          REFRESH_TOKEN_EXPIRED: ${{ secrets.REFRESH_TOKEN_EXPIRED }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ROLE_START_PAGE: ${{ secrets.ROLE_START_PAGE }}
          ROLE_PAGE_LIMIT: ${{ secrets.ROLE_PAGE_LIMIT }}
          AUTH_HISTORY_START_PAGE: ${{ secrets.AUTH_HISTORY_START_PAGE }}
          AUTH_HISTORY__PAGE_LIMIT: ${{ secrets.AUTH_HISTORY__PAGE_LIMIT }}
          YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
          YANDEX_CLIENT_SECRET: ${{ secrets.YANDEX_CLIENT_SECRET }}
          YANDEX_AUTHORIZE_URL: ${{ secrets.YANDEX_AUTHORIZE_URL }}
          YANDEX_ACCESS_TOKEN_URL: ${{ secrets.YANDEX_ACCESS_TOKEN_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REQUEST_LIMIT_PER_MINUTE: ${{ secrets.REQUEST_LIMIT_PER_MINUTE }}
          JAEGER_HOST: ${{ secrets.JAEGER_HOST }}
          JAEGER_PORT: ${{ secrets.JAEGER_PORT }}
          XCAPTCHA_SITE_KEY: ${{ secrets.XCAPTCHA_SITE_KEY }}
          XCAPTCHA_SECRET_KEY: ${{ secrets.XCAPTCHA_SECRET_KEY }}
          # Admin service
          DB_HOST_ADMIN: ${{ secrets.DB_HOST_ADMIN }}
          DB_PORT_ADMIN: ${{ secrets.DB_PORT_ADMIN }}
          DB_NAME_ADMIN: ${{ secrets.DB_NAME_ADMIN }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_DEBUG_FLAG: ${{ secrets.DJANGO_DEBUG_FLAG }}
          DJANGO_SUPERUSER_USERNAME: ${{ env.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD: ${{ env.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1gnn1cdso7c6e7ma8rp
          VM-name: ubuntu20-billing-ci
          vm-service-account-id: ajejfodg7dvfe92vh0vv
          vm-subnet-id: e9bcllc4me68a9dtjci0
          user-data-path: './user-data.yaml'
          docker-compose-path: './docker-compose.prod.yaml'